// Generated by gencpp from file kusv_msgs/DrivingMode.msg
// DO NOT EDIT!


#ifndef KUSV_MSGS_MESSAGE_DRIVINGMODE_H
#define KUSV_MSGS_MESSAGE_DRIVINGMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kusv_msgs
{
template <class ContainerAllocator>
struct DrivingMode_
{
  typedef DrivingMode_<ContainerAllocator> Type;

  DrivingMode_()
    : mode(false)  {
    }
  DrivingMode_(const ContainerAllocator& _alloc)
    : mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::kusv_msgs::DrivingMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kusv_msgs::DrivingMode_<ContainerAllocator> const> ConstPtr;

}; // struct DrivingMode_

typedef ::kusv_msgs::DrivingMode_<std::allocator<void> > DrivingMode;

typedef boost::shared_ptr< ::kusv_msgs::DrivingMode > DrivingModePtr;
typedef boost::shared_ptr< ::kusv_msgs::DrivingMode const> DrivingModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kusv_msgs::DrivingMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kusv_msgs::DrivingMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kusv_msgs::DrivingMode_<ContainerAllocator1> & lhs, const ::kusv_msgs::DrivingMode_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kusv_msgs::DrivingMode_<ContainerAllocator1> & lhs, const ::kusv_msgs::DrivingMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kusv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::DrivingMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::DrivingMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::DrivingMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::DrivingMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::DrivingMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::DrivingMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kusv_msgs::DrivingMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3124ebba8ebedcd8ba82847d482ceb7";
  }

  static const char* value(const ::kusv_msgs::DrivingMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3124ebba8ebedcdULL;
  static const uint64_t static_value2 = 0x8ba82847d482ceb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::kusv_msgs::DrivingMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kusv_msgs/DrivingMode";
  }

  static const char* value(const ::kusv_msgs::DrivingMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kusv_msgs::DrivingMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool mode\n"
;
  }

  static const char* value(const ::kusv_msgs::DrivingMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kusv_msgs::DrivingMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrivingMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kusv_msgs::DrivingMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kusv_msgs::DrivingMode_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUSV_MSGS_MESSAGE_DRIVINGMODE_H
